project:
  type: book
  preview:
    port: 4200
    browser: false

book:
  title: "Book Title"
  output-file: main
  author: "Book Author"
  date: "01/01/0000"
  image: cover.png
  image-alt: "Book Cover"
  isbn: "978-XXX"
  license: CC-BY-4.0
  language: en
  publisher: Konsensus Network
  favicon: /figures/freestarfish.png
  search:
    location: sidebar
    type: overlay
  sidebar:
    style: floating
    border: true
  navbar:
    left:
      - icon: book
        text: "Read online"
        href: index.qmd
        aria-label: Book
  page-footer:
    left:
      - text: "© 2025 Konsensus Network"
    center:
      - text: "License"
        href: index.qmd
      - text: "Presale"
        href: presale.qmd
    right:
      - icon: twitter
        href: https://twitter.com/konsensusn
        aria-label: Twitter
      - icon: github
        href: https://github.com/konsensusnetwork
        aria-label: Github
      - icon: linkedin
        href: https://www.linkedin.com/konsensusnetwork
        aria-label: LinkedIn
      - icon: youtube
        href: https://www.youtube.com/konsensusnetwork
        aria-label: YouTube
  open-graph: true
  twitter-card:
    site: "@konsensusn"
  chapters:
    - index.qmd
    - chapters/ch01.qmd
    - chapters/ch02.qmd
    - part: Part 2
      chapters:
        - chapters/ch03.qmd
        - chapters/ch04.qmd

format:
  html:
    lang: en
    theme:
      light: [flatly, theme.scss, theme-light.scss]
    number-depth: 2
    grid:
      sidebar-width: 500px
      body-width: 900px
      margin-width: 350px
      gutter-width: 1em
    toc: true
    toc-location: left
    reference-location: margin
  pdf:
    lang: en
    documentclass: memoir
    classoption: smalldemyvopaper,10pt,twoside,onecolumn,openright,extrafontsizes,hidelinks
    papersize: a5
    toc-depth: 1
    toc-title: Contents
    keep-tex: true
    colorlinks: false
    include-in-header:
      - preamble.tex
  epub:
    cover-image: cover.png
    cover-image-alt: |
      Book Cover
    creator: Konsensus Network
    toc: true
    toc-depth: 1
    toc-title: Contents
    lang: "en-UK"
    css: epub.css
    number-depth: 2